### ISSUE TITLE
报 fileList 未定义

### ISSUE THREAD

**Issue by MoJingYan** [shady-xia/vue-uploader-solutions-next#4]
我把 globalUpdload 组件拿过来用。一直报 fileList 未定义
`Cannot destructure property 'fileList' of 'undefined' as it is undefined.`
请指点一下

**Comment by 2450555169** [comment]
/[](![image](https://user-images.githubusercontent.com/61170204/232702730-9640d411-ebca-4fa1-a700-d3065ce01915.png))

**Comment by MoJingYan** [comment]
![image](https://user-images.githubusercontent.com/61170204/232702977-85fe16c7-fc67-42f0-9d3b-41383a1cb897.png)

**Comment by MoJingYan** [comment]
![image](https://user-images.githubusercontent.com/61170204/232703185-37c400aa-615f-419d-b42d-fa6e500a4af2.png)

**Comment by shady-xia** [comment]
检查一下`vue-simple-uploader`的版本，使用 `npm install vue-simple-uploader@next --save` 安装

**Comment by MoJingYan** [comment]
您的意思是我现有的项目直接把你项目里的GlobalUpload拿过来用是不行的，还需要下载 vue-simple-uploader 吗

**Comment by shady-xia** [comment]
对，我是基于这个插件封装的

**Comment by MoJingYan** [comment]
已解决！感谢~
